# Generated by Django 4.2.26 on 2026-05-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='readstat',
            index=models.Index(fields=['article', 'ip_address', '-created_at'], name='blog_readst_article_87f0c6_idx'),
        ),
    ]
